version: '3.7'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: tryiris

    ports:
    # 1972 is the superserver default port 
    - "1972:1972"
    # 52773 is the webserver/management portal port
    - "52773:52773"
   
    volumes:
    # Mounts a local directory for passing in files and test scripts
    - ./:/ISC
                                
    environment:
     - TZ=JST-9

  app:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
     - db
    ports:
      - 5000:5000
    environment:
      PYTHONPATH: '/opt/webapp/'
      PORT: '5000'