version: '3.2'

services:
  iris:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: testiris

    ports:
    # 1972 is the superserver default port 
    - "1972:1972"
    # 52773 is the webserver/management portal port
    - "52773:52773"
               
    environment:
     - TZ=JST-9